mysql:
  repo: git://github.com/simpsonjulian/puppet-mysql.git
  path: modules
passenger:
  repo: git://github.com/douglassquirrel/puppet-passenger.git
  path: modules
ubuntu:
  repo: git://github.com/simpsonjulian/puppet-ubuntu.git
  path: modules
nagios:
  repo: git://github.com/simpsonjulian/puppet-nagios.git
  path: modules
apache:
  repo: git://github.com/simpsonjulian/puppet-apache-ubuntu.git
  path: modules
rubygems:
  repo: git://github.com/simpsonjulian/puppet-rubygems.git
  path: modules
